- name: Design
  description: Modular consistent user interfaces for multi-purpose applications in the web or iOS crafted carefully with Sketch.

- name: Web Development
  description: Clean code for responsive websites, themes or templates. Multi-language content management systems and e-commerce integrations.